version: '3.8'
services:
  civic-voice-db:
    container_name: civic-voice-db
    image: postgres:16.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    ports:
      - '5432:5432'
    volumes: 
      - civic-voice-db:/var/lib/postgresql/data
      - ./database/sql/ddl/:/docker-entrypoint-initdb.d/
    networks:
      - ocv-network

  civic-voice-pgadmin4:
    image: dpage/pgadmin4:8.1
    container_name: civic-voice-pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    volumes:
      - civic-voice-pgadmin4:/var/lib/pgadmin
    networks:
      - ocv-network

  data-pipeline:
    container_name: data-pipeline
    restart: unless-stopped
    build: ./data-pipeline
    depends_on:
      - civic-voice-db
    environment:
      # Used to describe the database connection in /config/databasePool.ts
      - DB_HOST=civic-voice-db
    networks:
      - ocv-network

networks:
  ocv-network:
volumes:
  civic-voice-db:
  civic-voice-pgadmin4:
